### ISSUE TITLE
Selecting children or siblings when there aren't any breaks

### ISSUE THREAD

**Issue by d125q** [alexherbo2/selection.js#1]
There is no protection against selecting children or siblings when there aren't any.  I believe the code should be changed to do something similar to what [`parent` does](https://github.com/alexherbo2/selection.js/blob/c832a8dbb988fcb7a69e3c65c55f0b2170fb7928/scripts/selection.js#L76).

**Comment by alexherbo2** [comment]
@d125q I’ll look into it.  Thanks!
